
local config= {}
---@type ClassImages.ImagePiece[]
config.imagePieces = {
    {
        texture = "fill_A_L_Books_01",
        priority = 11,
        excludedPieces = { 121 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_L_Books_02",
        priority = 12,
        excludedPieces = { 121 },
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_L_Books_03",
        priority = 13,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_cuirass",
        priority = 20,
        excludedPieces = {},
        slots = { "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.unarmored },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_cuirass_sh",
        priority = 20,
        excludedPieces = {},
        slots = { "Background_Left" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.unarmored },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Books_01",
        priority = 31,
        excludedPieces = { 291 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_A_R_Books_02",
        priority = 32,
        excludedPieces = { 122 },
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "bk_scroll_open_pickssoulgems",
        priority = 40,
        excludedPieces = { 50, 60, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.enchant },
            { type = tes3.skill.security },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "bk_scroll_open_picks",
        priority = 50,
        excludedPieces = { 40, 60, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.security },
            { type = tes3.skill.enchant, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "bk_scroll_open_soulgems",
        priority = 60,
        excludedPieces = { 40, 50, 70, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.enchant },
            { type = tes3.skill.security, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "bk_scroll_open",
        priority = 70,
        excludedPieces = { 120, 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft, major = true },
            { type = tes3.skill.security, negative = true },
            { type = tes3.skill.enchant, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.stealth },
        },
    },
    {
        texture = "weap_spear",
        priority = 80,
        excludedPieces = {},
        slots = { "Below_Left_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.spear },
            { type = tes3.skill.acrobatics },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_alembic",
        priority = 90,
        excludedPieces = {},
        slots = { "Background_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy },
            { type = tes3.skill.restoration },
            { type = tes3.skill.mercantile },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_ingred",
        priority = 100,
        excludedPieces = {},
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy }
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_waraxe",
        priority = 110,
        excludedPieces = {},
        slots = { "Above_Left_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat, negative = true },
        },
    },
    {
        texture = "fill_B_M_Books_01",
        priority = 121,
        excludedPieces = { 11, 12 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_B_M_Books_02",
        priority = 122,
        excludedPieces = { 32 },
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_B_M_Books_03",
        priority = 123,
        excludedPieces = {},
        slots = { "Background_Middle", "Midground_Middle" },
        shieldState = "noShield",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "bk_note",
        priority = 130,
        excludedPieces = { 40, 50, 60, 70, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_1" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_gloves",
        priority = 140,
        excludedPieces = { 130, 340, 350 },
        slots = { "Foreground_Left", "Below_Left_3" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.handToHand, major = true },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_hammer",
        priority = 150,
        excludedPieces = {},
        slots = { "Midground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer, negative = true },
            { type = tes3.skill.heavyArmor },
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance, negative = true },
			{ type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword_ssword",
        priority = 160,
        excludedPieces = { 170, 410, 420 },
        slots = { "Below_Right_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
            { type = tes3.skill.shortBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_ssword",
        priority = 170,
        excludedPieces = { 160 },
        slots = { "Below_Right_1" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.shortBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_gems",
        priority = 180,
        excludedPieces = {},
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.athletics },
            { type = tes3.skill.acrobatics },
            { type = tes3.skill.security, major = true },
            { type = tes3.skill.sneak, major = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_staff",
        priority = 190,
        excludedPieces = {},
        slots = { "Below_Left_4" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon },
            { type = tes3.skill.unarmored, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_tower",
        priority = 200,
        excludedPieces = { 210, 220 },
        slots = { "Background_Left", "Background_Middle", "Midground_Left", "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.heavyArmor, major = true },
            { type = tes3.skill.block },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_iron",
        priority = 210,
        excludedPieces = { 200, 220 },
        slots = { "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.block },
            { type = tes3.skill.mediumArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_shield_netch",
        priority = 220,
        excludedPieces = { 200, 210 },
        slots = { "Midground_Middle" },
        shieldState = "isShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.block },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_lute",
        priority = 230,
        excludedPieces = {},
        slots = { "Above_Right_1" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
        classRequirements = {
            { type = "bard" }
        }
    },
    {
        texture = "armo_boots_leather",
        priority = 240,
        excludedPieces = { 250 },
        slots = { "Background_Right", "Midground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mediumArmor },
            { type = tes3.skill.lightArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "armo_boots_netch",
        priority = 250,
        excludedPieces = { 240 },
        slots = { "Midground_Right", "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.lightArmor },
            { type = tes3.skill.sneak },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_picks",
        priority = 261,
        excludedPieces = {},
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.security},
            { type = tes3.skill.speechcraft},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_picks_gold",
        priority = 262,
        excludedPieces = { 340, 350 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.security},
            { type = tes3.skill.speechcraft, negative = true },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_warhammer",
        priority = 270,
        excludedPieces = {},
        slots = { "Background_Right", "Midground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
	{
        texture = "fill_C_L_Books_01",
        priority = 281,
        excludedPieces = { 31 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_L_Books_02",
        priority = 282,
        excludedPieces = { 291, 320 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_L_Books_03",
        priority = 283,
        excludedPieces = { 292 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_R_Books_01",
        priority = 291,
        excludedPieces = { 282, 320 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "fill_C_R_Books_02",
        priority = 292,
        excludedPieces = { 283 },
        slots = { "Foreground_Right" },
        shieldState = "none",
        isGold = false,
        isFiller = true,
        skillRequirements = {},
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_dagger",
        priority = 300,
        excludedPieces = {},
        slots = { "Below_Right_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.shortBlade, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_mortar",
        priority = 310,
        excludedPieces = {},
        slots = { "Midground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.alchemy},
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type =tes3.specialization.magic },
        },
    },
    {
        texture = "misc_soulgems",
        priority = 320,
        excludedPieces = { 282 },
        slots = { "Foreground_Left" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.enchant},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_waraxe_sh",
        priority = 330,
        excludedPieces = {},
        slots = { "Above_Left_1" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength, negative = true },
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat, negative = true },
        },
    },
    {
        texture = "misc_gold_CR",
        priority = 340,
        excludedPieces = { 350 },
        slots = { "Foreground_Right", "Below_Right_3" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mercantile },
            { type = tes3.skill.sneak },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true
    },
    {
        texture = "misc_gold_CL",
        priority = 350,
        excludedPieces = { 340 },
        slots = { "Foreground_Left", "Below_Left_5" },
        shieldState = "none",
        isGold = true,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.mercantile },
            { type = tes3.skill.sneak },
            { type = tes3.skill.speechcraft },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
		isOr = true
    },
    {
        texture = "weap_club",
        priority = 360,
        excludedPieces = {},
        slots = { "Above_Left_2" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon, major = true},
            { type = tes3.skill.unarmored},
        },
        attributeRequirements = {},
        specialisationRequirements = {
            { type = tes3.specialization.combat },
        },
    },
    {
        texture = "weap_stars",
        priority = 370,
        excludedPieces = {},
        slots = { "Above_Left_3" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman},
            { type = tes3.skill.sneak},
        },
        attributeRequirements = {
            { type = tes3.attribute.agility},
            { type = tes3.attribute.speed},
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_battleaxe",
		priority = 380,
		excludedPieces = {},
		slots = { "Above_Left_4" },
		shieldState = "noShield",
        isGold = false,
		isFiller = false,
		skillRequirements = {
			{ type = tes3.skill.axe},
		},
		attributeRequirements = {
			{ type = tes3.attribute.strength},
		},
		specialisationRequirements = {
			{ type = tes3.specialization.combat },
		},
	},
    {
        texture = "weap_battleaxe_sh",
        priority = 390,
        excludedPieces = {},
        slots = { "Above_Left_4" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.axe},
        },
        attributeRequirements = {
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {
            { type = tes3.specialization.combat },
        },
    },
    {
        texture = "armo_helm",
        priority = 400,
        excludedPieces = {},
        slots = { "Above_Left_5" },
        shieldState = "none",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.heavyArmor },
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword",
        priority = 410,
        excludedPieces = { 160, 420 },
        slots = { "Below_Right_1" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_lsword_sh",
        priority = 420,
        excludedPieces = { 160, 420 },
        slots = { "Above_Right_2" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.longBlade},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_mace",
        priority = 430,
        excludedPieces = {},
        slots = { "Above_Right_3" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_mace_sh",
        priority = 440,
        excludedPieces = {},
        slots = { "Above_Right_3" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.bluntWeapon},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "misc_repairkit",
        priority = 450,
        excludedPieces = {},
        slots = { "Above_Right_4" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer},
            { type = tes3.skill.heavyArmor},
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance},
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {},
    },

    {
        texture = "misc_repairkit_sh",
        priority = 460,
        excludedPieces = {},
        slots = { "Above_Right_4" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.armorer},
            { type = tes3.skill.heavyArmor},
        },
        attributeRequirements = {
            { type = tes3.attribute.endurance},
            { type = tes3.attribute.strength},
        },
        specialisationRequirements = {},
    },
    {
        texture = "weap_bow",
        priority = 470,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, minor = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bow_sh",
        priority = 480,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, minor = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bowarrows",
        priority = 490,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "noShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
    {
        texture = "weap_bowarrows_sh",
        priority = 500,
        excludedPieces = {},
        slots = { "Above_Right_5" },
        shieldState = "requiresShield",
        isGold = false,
        isFiller = false,
        skillRequirements = {
            { type = tes3.skill.marksman, major = true},
        },
        attributeRequirements = {},
        specialisationRequirements = {},
    },
}

return config